# Generated by Django 4.2.16 on 2024-11-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0002_rename_abourus_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='Image',
        ),
    ]
