# Generated by Django 4.2.16 on 2024-11-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0003_remove_aboutus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
